### PR TITLE
UploadPhoto Update

### PR DESCRIPTION
**Pull request by codexJoin**
Updated uploadPhoto.
This update allow only jpeg images..

### CODE REVIEW

**Comment by tydegennaro** [comment]
Do you have an email, twitter, or telegram I can contact you at? Have some questions on what you did.

**Comment by codexJoin** [comment]
Ready!

**Comment by ozanilbey** [comment]
Hi @revall, will this PR be merged anytime soon?

**Comment by revall** [comment]
Merged after refactoring #165

**Pull request closed without merging**
